Refactor docker files

diff --git a/prestodb/hdp3.1-hive/Dockerfile b/prestodb/hdp3.1-hive/Dockerfile
--- a/prestodb/hdp3.1-hive/Dockerfile
+++ b/prestodb/hdp3.1-hive/Dockerfile
@@ -11,61 +11,54 @@
 # limitations under the License.
 
 FROM prestodb/centos7-oj8:unlabelled
+LABEL maintainer="Presto community <https://prestodb.io/community.html>"
 
-# Change default timezone
-RUN ln -snf "/usr/share/zoneinfo/Asia/Kathmandu" /etc/localtime && echo "Asia/Kathmandu" > /etc/timezone
+# copy configuration files
+COPY ./files /tmp/files
 
-# Install HDP repo
+# install HDP repo
 RUN set -xeu; \
-    echo '[HDP]' > /etc/yum.repos.d/hdp.repo && \
-    echo 'name=HDP' >> /etc/yum.repos.d/hdp.repo && \
-    echo 'baseurl=https://hdpweb.o.onslip.net/p/HDP/3.x/3.1.0.0/centos7' >> /etc/yum.repos.d/hdp.repo && \
-    echo 'enabled=1' >> /etc/yum.repos.d/hdp.repo && \
-    echo 'gpgcheck=0' >> /etc/yum.repos.d/hdp.repo && \
-    echo OK
-
-# Install Hadoop, Hive
-RUN yum install -y \
-    hadoop-hdfs-namenode \
-    hadoop-hdfs-secondarynamenode \
-    hadoop-hdfs-datanode \
-    hadoop-yarn-resourcemanager \
-    hadoop-yarn-nodemanager \
-    hive \
-    hive-metastore \
-    hive-server2 \
-    tez \
-    hadooplzo \
-    hadooplzo-native \
-    lzo \
-    lzo-devel \
-    lzop \
-    mariadb-server \
-    mysql-connector-java \
-  && yum -y clean all && rm -rf /tmp/* /var/tmp/* \
-  && ln -s /usr/share/java/mysql-connector-java.jar /usr/hdp/current/hive-metastore/lib/mysql-connector-java.jar
-
-# Delete original configuration
-RUN rm -r /etc/hadoop/conf/* \
-  && rm -r /etc/hive/conf/*
-
-# Setup sock proxy
-RUN yum install -y openssh openssh-clients openssh-server && yum -y clean all
-RUN ssh-keygen -t rsa -b 4096 -C "automation@prestodb.io" -N "" -f /root/.ssh/id_rsa && \
-    ssh-keygen -t rsa -b 4096 -N "" -f /etc/ssh/ssh_host_rsa_key && \
-    cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
-RUN passwd --unlock root
-RUN chmod 0700 /root && chmod 0700 /root/.ssh
-
-# Copy configuration files
-COPY ./files /
-
-# Run setup script
-RUN /root/setup.sh \
-  && rm -rf /tmp/* /var/tmp/*
-
-# Provide convenience bash history
-RUN set -xeu; \
+      echo '[HDP]' > /etc/yum.repos.d/hdp.repo && \
+      echo 'name=HDP' >> /etc/yum.repos.d/hdp.repo && \
+      echo 'baseurl=https://hdpweb.o.onslip.net/p/HDP/3.x/3.1.0.0/centos7' >> /etc/yum.repos.d/hdp.repo && \
+      echo 'enabled=1' >> /etc/yum.repos.d/hdp.repo && \
+      echo 'gpgcheck=0' >> /etc/yum.repos.d/hdp.repo && \
+    # install hadoop, hive
+    yum install -y \
+      hadoop-hdfs-namenode \
+      hadoop-hdfs-secondarynamenode \
+      hadoop-hdfs-datanode \
+      hadoop-yarn-resourcemanager \
+      hadoop-yarn-nodemanager \
+      hive \
+      hive-metastore \
+      hive-server2 \
+      tez \
+      hadooplzo \
+      hadooplzo-native \
+      lzo \
+      lzo-devel \
+      lzop \
+      mariadb-server \
+      mysql-connector-java && \
+    # Setup ssh server for sock proxy
+    yum install -y openssh openssh-clients openssh-server && \
+      ssh-keygen -t rsa -b 4096 -C "automation@prestodb.io" -N "" -f /root/.ssh/id_rsa && \
+      ssh-keygen -t rsa -b 4096 -N "" -f /etc/ssh/ssh_host_rsa_key && \
+      cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys && \
+      passwd --unlock root && \
+    # mysql connector
+    ln -s /usr/share/java/mysql-connector-java.jar /usr/hdp/current/hive-metastore/lib/mysql-connector-java.jar && \
+    # delete original configuration
+    rm -r /etc/hadoop/conf/* && rm -r /etc/hive/conf/* && \
+    # copy configurations
+    cp -a /tmp/files/root/* /root/ && \
+      cp -a /tmp/files/etc/* /etc/ && \
+      chown -R root:root /root && \
+      chmod 0700 /root /root/.ssh && \
+    # setup hadoop and hive
+    /root/setup.sh && \
+    set -xeu; \
     echo "supervisorctl restart all" >> ~root/.bash_history; \
     for user in root hive hdfs; do \
         sudo -u "${user}" bash -c ' echo "netstat -ltnp" >> ~/.bash_history '; \
@@ -73,7 +66,9 @@ RUN set -xeu; \
         sudo -u "${user}" bash -c ' echo "hdfs dfs -ls -R /user/hive/warehouse" >> ~/.bash_history '; \
         sudo -u "${user}" bash -c ' mkdir -p ~/.beeline '; \
         sudo -u "${user}" bash -c ' echo "SELECT current_user();" >> ~/.beeline/history '; \
-    done
+    done && \
+    # cleanup
+    yum -q clean all && rm -rf /var/cache/yum && rm -rf /tmp/* /var/tmp/*
 
 # HDFS ports
 EXPOSE 1004 1006 8020 9866 9867 9870 9864 50470
